import Head from "next/head";
import dynamic from "next/dynamic";
import Loader from "react-loader-spinner";
import { getData } from "../lib/ParseCSV";
import "react-loader-spinner/dist/loader/css/react-spinner-loader.css";

export default function Home() {
  const Map = dynamic(
    () => import("../components/Map"), // replace '@components/map' with your component's location
    {
      loading: () => (
        <div className="loader">
          <Loader
            type="Audio"
            color="#00BFFF"
            height={100}
            width={100}
          />
        </div>
      ),
      ssr: false, // This line is important. It's what prevents server-side render
    }
  );

  return (
    <div>
      <Head>
        <title>Parkour Nearby</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Map />
    </div>
  );
}
